CREATE TYPE "RecebimentoStatus" AS ENUM ('PENDING','IN_PROGRESS','PARTIALLY_COMPLETED','COMPLETED','REJECTED'); CREATE TYPE "MovimentacaoEstoqueTipo" AS ENUM ('ENTRY','RESERVE','RELEASE_RESERVATION','EXIT','ADJUSTMENT_POSITIVE','ADJUSTMENT_NEGATIVE','RETURN_ENTRY','RETURN_EXIT'); CREATE TYPE "MovimentacaoEstoqueMotivo" AS ENUM ('PURCHASE_RECEIPT','SALE','MANUAL_CORRECTION','DAMAGE','LOSS','RETURN','RESERVATION','RESERVATION_RELEASE');
CREATE TABLE "Recebimento"("id" TEXT PRIMARY KEY,"lojaId" TEXT NOT NULL,"viagemId" TEXT NOT NULL,"malaId" TEXT NOT NULL,"status" "RecebimentoStatus" NOT NULL DEFAULT 'PENDING',"iniciadoEm" TIMESTAMP(3) NOT NULL,"concluidoEm" TIMESTAMP(3),"confirmadoPorId" TEXT NOT NULL,"observacoes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL); CREATE UNIQUE INDEX "Recebimento_id_lojaId_key" ON "Recebimento"("id","lojaId"); CREATE INDEX "Recebimento_lojaId_status_idx" ON "Recebimento"("lojaId","status");
CREATE TABLE "RecebimentoItem"("id" TEXT PRIMARY KEY,"lojaId" TEXT NOT NULL,"recebimentoId" TEXT NOT NULL,"pedidoCompraItemId" TEXT NOT NULL,"produtoId" TEXT NOT NULL,"quantidadeEsperada" INTEGER NOT NULL,"quantidadeRecebida" INTEGER NOT NULL DEFAULT 0,"quantidadeRejeitada" INTEGER NOT NULL DEFAULT 0,"observacoes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL); CREATE UNIQUE INDEX "RecebimentoItem_recebimentoId_pedidoCompraItemId_key" ON "RecebimentoItem"("recebimentoId","pedidoCompraItemId"); CREATE INDEX "RecebimentoItem_lojaId_produtoId_idx" ON "RecebimentoItem"("lojaId","produtoId");
CREATE TABLE "Estoque"("id" TEXT PRIMARY KEY,"lojaId" TEXT NOT NULL,"produtoId" TEXT NOT NULL,"quantidadeFisica" INTEGER NOT NULL DEFAULT 0,"quantidadeReservada" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL); CREATE UNIQUE INDEX "Estoque_lojaId_produtoId_key" ON "Estoque"("lojaId","produtoId"); CREATE UNIQUE INDEX "Estoque_id_lojaId_key" ON "Estoque"("id","lojaId");
CREATE TABLE "MovimentacaoEstoque"("id" TEXT PRIMARY KEY,"lojaId" TEXT NOT NULL,"produtoId" TEXT NOT NULL,"estoqueId" TEXT NOT NULL,"recebimentoId" TEXT,"tipo" "MovimentacaoEstoqueTipo" NOT NULL,"motivo" "MovimentacaoEstoqueMotivo" NOT NULL,"quantidade" INTEGER NOT NULL,"quantidadeAnterior" INTEGER NOT NULL,"quantidadePosterior" INTEGER NOT NULL,"responsavelId" TEXT NOT NULL,"observacoes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE INDEX "MovimentacaoEstoque_lojaId_produtoId_createdAt_idx" ON "MovimentacaoEstoque"("lojaId","produtoId","createdAt"); CREATE INDEX "MovimentacaoEstoque_lojaId_tipo_idx" ON "MovimentacaoEstoque"("lojaId","tipo");
ALTER TABLE "Recebimento" ADD CONSTRAINT "Recebimento_lojaId_fkey" FOREIGN KEY("lojaId") REFERENCES "Loja"("id"),ADD CONSTRAINT "Recebimento_viagemId_lojaId_fkey" FOREIGN KEY("viagemId","lojaId") REFERENCES "Viagem"("id","lojaId"),ADD CONSTRAINT "Recebimento_malaId_lojaId_fkey" FOREIGN KEY("malaId","lojaId") REFERENCES "Mala"("id","lojaId"),ADD CONSTRAINT "Recebimento_confirmadoPorId_fkey" FOREIGN KEY("confirmadoPorId") REFERENCES "Usuario"("id");
ALTER TABLE "RecebimentoItem" ADD CONSTRAINT "RecebimentoItem_lojaId_fkey" FOREIGN KEY("lojaId") REFERENCES "Loja"("id"),ADD CONSTRAINT "RecebimentoItem_recebimentoId_lojaId_fkey" FOREIGN KEY("recebimentoId","lojaId") REFERENCES "Recebimento"("id","lojaId") ON DELETE CASCADE,ADD CONSTRAINT "RecebimentoItem_pedidoCompraItemId_lojaId_fkey" FOREIGN KEY("pedidoCompraItemId","lojaId") REFERENCES "PedidoCompraItem"("id","lojaId"),ADD CONSTRAINT "RecebimentoItem_produtoId_lojaId_fkey" FOREIGN KEY("produtoId","lojaId") REFERENCES "Produto"("id","lojaId");
ALTER TABLE "Estoque" ADD CONSTRAINT "Estoque_lojaId_fkey" FOREIGN KEY("lojaId") REFERENCES "Loja"("id"),ADD CONSTRAINT "Estoque_produtoId_lojaId_fkey" FOREIGN KEY("produtoId","lojaId") REFERENCES "Produto"("id","lojaId");
ALTER TABLE "MovimentacaoEstoque" ADD CONSTRAINT "MovimentacaoEstoque_lojaId_fkey" FOREIGN KEY("lojaId") REFERENCES "Loja"("id"),ADD CONSTRAINT "MovimentacaoEstoque_produtoId_lojaId_fkey" FOREIGN KEY("produtoId","lojaId") REFERENCES "Produto"("id","lojaId"),ADD CONSTRAINT "MovimentacaoEstoque_estoqueId_lojaId_fkey" FOREIGN KEY("estoqueId","lojaId") REFERENCES "Estoque"("id","lojaId"),ADD CONSTRAINT "MovimentacaoEstoque_recebimentoId_lojaId_fkey" FOREIGN KEY("recebimentoId","lojaId") REFERENCES "Recebimento"("id","lojaId"),ADD CONSTRAINT "MovimentacaoEstoque_responsavelId_fkey" FOREIGN KEY("responsavelId") REFERENCES "Usuario"("id");
