CREATE TYPE "PedidoCompraStatus" AS ENUM ('DRAFT','PLACED','CONFIRMED','PARTIALLY_RECEIVED_MIAMI','RECEIVED_MIAMI','ALLOCATED_TO_TRIP','IN_TRANSIT_BRAZIL','ARRIVED_BRAZIL','COMPLETED','CANCELLED');
CREATE TABLE "Fornecedor" ("id" TEXT NOT NULL,"lojaId" TEXT NOT NULL,"nome" TEXT NOT NULL,"nomeFantasia" TEXT,"site" TEXT,"email" TEXT,"telefone" TEXT,"pais" TEXT,"moedaPadrao" TEXT,"observacoes" TEXT,"ativo" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Fornecedor_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PedidoCompra" ("id" TEXT NOT NULL,"lojaId" TEXT NOT NULL,"fornecedorId" TEXT NOT NULL,"numeroPedido" TEXT NOT NULL,"dataCompra" TIMESTAMP(3) NOT NULL,"moeda" TEXT NOT NULL DEFAULT 'USD',"status" "PedidoCompraStatus" NOT NULL DEFAULT 'DRAFT',"descontoPedido" DECIMAL(12,2) NOT NULL DEFAULT 0,"frete" DECIMAL(12,2) NOT NULL DEFAULT 0,"imposto" DECIMAL(12,2) NOT NULL DEFAULT 0,"subtotal" DECIMAL(12,2) NOT NULL DEFAULT 0,"total" DECIMAL(12,2) NOT NULL DEFAULT 0,"observacoes" TEXT,"canceladoEm" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "PedidoCompra_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PedidoCompraItem" ("id" TEXT NOT NULL,"pedidoCompraId" TEXT NOT NULL,"lojaId" TEXT NOT NULL,"produtoId" TEXT NOT NULL,"quantidade" INTEGER NOT NULL,"quantidadeRecebidaMiami" INTEGER NOT NULL DEFAULT 0,"precoUnitario" DECIMAL(12,2) NOT NULL,"descontoItem" DECIMAL(12,2) NOT NULL DEFAULT 0,"totalItem" DECIMAL(12,2) NOT NULL,"observacoes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "PedidoCompraItem_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Fornecedor_lojaId_ativo_idx" ON "Fornecedor"("lojaId","ativo");
CREATE INDEX "Fornecedor_lojaId_nome_idx" ON "Fornecedor"("lojaId","nome");
CREATE UNIQUE INDEX "Fornecedor_id_lojaId_key" ON "Fornecedor"("id","lojaId");
CREATE INDEX "PedidoCompra_lojaId_status_idx" ON "PedidoCompra"("lojaId","status");
CREATE INDEX "PedidoCompra_lojaId_fornecedorId_idx" ON "PedidoCompra"("lojaId","fornecedorId");
CREATE INDEX "PedidoCompra_lojaId_dataCompra_idx" ON "PedidoCompra"("lojaId","dataCompra");
CREATE UNIQUE INDEX "PedidoCompra_lojaId_fornecedorId_numeroPedido_key" ON "PedidoCompra"("lojaId","fornecedorId","numeroPedido");
CREATE UNIQUE INDEX "PedidoCompra_id_lojaId_key" ON "PedidoCompra"("id","lojaId");
CREATE INDEX "PedidoCompraItem_lojaId_produtoId_idx" ON "PedidoCompraItem"("lojaId","produtoId");
CREATE INDEX "PedidoCompraItem_lojaId_pedidoCompraId_idx" ON "PedidoCompraItem"("lojaId","pedidoCompraId");
CREATE UNIQUE INDEX "PedidoCompraItem_pedidoCompraId_produtoId_key" ON "PedidoCompraItem"("pedidoCompraId","produtoId");
CREATE UNIQUE INDEX "Produto_id_lojaId_key" ON "Produto"("id","lojaId");
ALTER TABLE "Fornecedor" ADD CONSTRAINT "Fornecedor_lojaId_fkey" FOREIGN KEY ("lojaId") REFERENCES "Loja"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PedidoCompra" ADD CONSTRAINT "PedidoCompra_lojaId_fkey" FOREIGN KEY ("lojaId") REFERENCES "Loja"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PedidoCompra" ADD CONSTRAINT "PedidoCompra_fornecedorId_lojaId_fkey" FOREIGN KEY ("fornecedorId","lojaId") REFERENCES "Fornecedor"("id","lojaId") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PedidoCompraItem" ADD CONSTRAINT "PedidoCompraItem_lojaId_fkey" FOREIGN KEY ("lojaId") REFERENCES "Loja"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PedidoCompraItem" ADD CONSTRAINT "PedidoCompraItem_pedidoCompraId_lojaId_fkey" FOREIGN KEY ("pedidoCompraId","lojaId") REFERENCES "PedidoCompra"("id","lojaId") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PedidoCompraItem" ADD CONSTRAINT "PedidoCompraItem_produtoId_lojaId_fkey" FOREIGN KEY ("produtoId","lojaId") REFERENCES "Produto"("id","lojaId") ON DELETE RESTRICT ON UPDATE CASCADE;
