import express from "express";
import cors from "cors";
import helmet from "helmet";
import { env } from "./lib/env";
import { errorHandler } from "./middlewares/error";
import { authRouter } from "./modules/auth/auth.routes";
import { categoriesRouter } from "./modules/categories/categories.routes";
import { productsRouter } from "./modules/products/products.routes";
import { suppliersRouter } from "./modules/suppliers/suppliers.routes";
import { purchaseOrdersRouter } from "./modules/purchase-orders/purchase-orders.routes";
import { logisticsRouter } from "./modules/logistics/logistics.routes";
import { receivingRouter } from "./modules/receiving/receiving.routes";
import { inventoryRouter } from "./modules/inventory/inventory.routes";
import { financeRouter } from "./modules/finance/finance.routes";
import { analyticsRouter } from "./modules/analytics/analytics.routes";
import { simulationRouter } from "./modules/simulation/simulation.routes";
import { operationsRouter } from "./modules/operations/operations.routes";
import { unifiedPurchasesRouter } from "./modules/unified-purchases/unified-purchases.routes";

export function createApp() {
  const app = express();
  app.use(helmet());
  app.use(cors({ origin: env.WEB_ORIGIN, credentials: true }));
  app.use(express.json());
  app.get("/health", (_req, res) => res.json({ status: "ok" }));
  app.use("/auth", authRouter);
  app.use("/categories", categoriesRouter);
  app.use("/products", productsRouter);
  app.use("/suppliers", suppliersRouter);
  app.use("/purchase-orders", purchaseOrdersRouter);
  app.use("/logistics", logisticsRouter);
  app.use("/receiving", receivingRouter);
  app.use("/inventory", inventoryRouter);
  app.use("/finance", financeRouter);
  app.use("/analytics", analyticsRouter);
  app.use("/simulations", simulationRouter);
  app.use("/operations", operationsRouter);
  app.use("/imported-purchases", unifiedPurchasesRouter);
  app.use(errorHandler);
  return app;
}
